### ISSUE TITLE
Cannot type letter "b" when running console.py

### ISSUE THREAD

**Issue by MartinBober** [hansl/mumble-bots#1]
While testing your project (wonderful idea, thank you so far), I notice that I cannot type the letter "b", not even in arguments. That's unexpected and kind of a problem because my Mumble server's hostname contains that letter several times, so I cannot call `connect ...`

**Comment by hansl** [comment]
I don't see this problem. I can type everything. Do you have a inputrc file which could interfere with the console?

I'm not doing any kind of magic with the console. It's a simple raw_input() call with the readline module included. Readline will take ~/.inputrc file into account though, so maybe there's something in there.
